### ISSUE TITLE
챕터2 44p cin입력 질문

### ISSUE THREAD

**Issue by JangIn-40** [mystous/DoItCPP#1]
안녕하세요 저자님! 책 잘 읽고 있습니다.
다름이 아니라 cin입력은 데이터의 형식을 확인하고 잘못되었으면 오류가 발생한다고 책에 나와있어서 실습코드에서 int형을 입력받는 변수 i(num_1)에 문자열을 입력해보았는데 일단 입력은 되던데 혹시 어떤식으로 오류가 발생하는걸까요? 실습환경은 visual studio 2022이고 윈도우입니다. 문자열을 입력할시 i를 출력해보았는데 i는 0으로 출력이 됐습니다.

**Comment by DesignMoon** [comment]
먼저 첫 질문을 남겨주셔서 반갑습니다 :)

cin을 이용하여 입력을 받을 때, 예상되는 데이터 형식과 다른 데이터가 입력될 수 있습니다. 이러한 경우 cin.fail() 함수를 사용하여 오류를 확인하고 처리할 수 있습니다.

cin.fail()은 C++의 표준 라이브러리인 <iostream>에서 제공하는 함수 중 하나입니다. 
cin.fail() 함수는 bool 값을 반환하며, 입력 작업에서 오류가 발생하면 true를 반환합니다. 이를 통해 오류 발생 여부를 확인하고 대응할 수 있지요.

이해하기 쉽도록 간단한 예제 코드를 하나 만들어드릴께요.

```cpp
#include <iostream>

int main() {
    int number;

    std::cout << "정수를 입력하세요: ";
    std::cin >> number;

    if (std::cin.fail()) {
        std::cerr << "입력된 데이터가 정수 형식이 아닙니다." << std::endl;
        return 1;
    }

    std::cout << "입력된 숫자는: " << number << std::endl;

    return 0;
}
```

추가로 궁금한 부분은 부담없이 글 남겨주세요. :)

**Comment by JangIn-40** [comment]
cin.fail()이라는 함수가 있었네요! 답변 감사합니다.
