### ISSUE TITLE
챕터12 460p 오탈자 문의

### ISSUE THREAD

**Issue by JangIn-40** [mystous/DoItCPP#10]
안녕하세요 저자님!
다름이 아니라 460p 실습 마지막줄 myListpush_front(0);가 아니라 myList.push_front(0);일거 같아 문의드립니다. 감사합니다.

**Comment by DesignMoon** [comment]
열심히 공부하시는 독자님 :)
짚어주신대로 해당부분은 오탈자가 맞습니다.
정오표에 반영하도록 하겠습니다!
