### ISSUE TITLE
챕터 14 539p 동적 할당 메모리 관련 질문, 527p 오탈자 문의

### ISSUE THREAD

**Issue by JangIn-40** [mystous/DoItCPP#11]
안녕하세요 저자님! 계속 잘 보고 있습니다.
다름이 아니라 챕터 14 539p 두번째 문단 첫번째 줄에 **동적 메모리는 힙 영역에 할당되므로 직접 해제하지 않으면 프로그램이 종료되어도 할당된 상태로 남아 있는다**라고 쓰여있는데 챕터3 115p 4번째 문단 두번째 줄에 **힙에 할당된 메모리는 명시적으로 해제하기 전에는 해당 프로그램이 종료될 때까지 계속 유지됩니다**라고 쓰여있습니다. 챕터3에서는 힙에 할당된 메모리를 해제하지 않아도 프로그램이 종료되면 메모리가 해제되는 것으로 이해했는데 챕터 14에서 읽은 내용으론 프로그램이 종료되도 메모리가 해제되지 않고 남아있는 것인 것 같아 제가 잘못 이해한 것인지 헷갈려 문의를 드립니다. 그리고 527p 두번째 문단 세번째줄에 consexpr이라고 적혀있는데 constexpr일 거 같아 문의드립니다. 감사합니다.

**Comment by mystous** [comment]
안녕하세요?

놓치기 쉬운 부분인데 찾아 주셔서 감사합니다.  
우선 간단하게 정리하면 115p의 내용이 539p의 내용보다는 맞습니다.

복잡한 내용을 설명 드리면
동적으로 할당된 메모리를 직접 해제하지 않으면 프로그램이 종료 되어도 메모리가 해제되지 않아 공용 리소스로 회수되지 않습니다. (방금 이 내용이 틀렸다고 했는데 무슨 소리인지 의아하실겁니다. 조금 더 읽어 주세요.)

프로그램은 늘 잘못된 가능성이 있습니다. 논리적으로 메모리를 해제하더라도 다양한 이유로 중단이 되면 메모리가 해제되지 않고 남아 있을 수 있습니다. 이렇게 방치된 메모리는 OS에 치명적인 문제를 발생시킬 수 있습니다.

그래서 OS가 프로그램이 실행이 되면 메모리 등 다양한 접근을 관찰하고 있습니다. 
메모리가 논리적으로 해제가 되지 않거나 알수 없는 이유로 중단이 되어 해제가 안되면
OS가 해제되지 않은 메모리를 회수하여 공용 자원으로 되돌립니다. 이 과정을 어떻게 보느냐에 따라서  115p의 내용이 맞기도 하고 539p의 내용이 맞기도 합니다.

이 부분은 공저자님과 논의 하여 내용 수정 방향을 정하고 이 쓰레드에 남겨 놓도록 하겠습니다.

매와 같은 눈으로 찾아 주신 내용 너무나 감사합니다.

**Comment by JangIn-40** [comment]
해제되지 않은 메모리를 회수하는 역할이 OS역할중의 하나군요! 운영체제도 공부를 따로 해야겠네요. 답변 감사합니다!

**Comment by mystous** [comment]
말씀 주신 내용은 115페이지, 539페이지 내용 통일해서 다음 쇄에 반영 하도록 하겠습니다. 
수정 방향은 아래와 같습니다.

 => 동적으로 할당된 메모리는 프로그램이 종료되어도 회수되지 않아 메모리 누수가 발생, 현대 OS에서는 이를 강제로 회수하는 기능을 지원함. 그래서 메모리가 회수되지 않고 프로그램이 종료 되면 Segement Fault가 발새함

감사합니다.
