### ISSUE TITLE
챕터 16 583p 오탈자 문의 + 감사합니다.

### ISSUE THREAD

**Issue by JangIn-40** [mystous/DoItCPP#12]
안녕하세요 저자님 그동안 책 정말 잘 읽었습니다.
마지막에 이렇게 인사를 드릴 수 있게 오탈자를 발견하게 되어서 좋다고 해야할까요? ㅎㅎ; 오탈자는 583p 3분퀴즈 모범답안의 1-1이 strong_oder가 아닌 strong_order이지 않을까 싶습니다.  그리고 정말 감사하다는 말씀을 드리고 싶습니다. 저자님과 책 덕분에 게을러졌을때 다시 시작할 수 있게 되었고, 그걸 이겨내고 책을 완독하니 뭔가 성취감이라고 해야할까요? 그런게 느껴져서 정말 좋았습니다. 더 글을쓰면 너무 횡설수설할거 같아 이만 줄이겠습니다. 감사합니다!

**Comment by mystous** [comment]
@JangIn-40  독자님, 안녕하세요?

먼저 완독을 너무 축하 드립니다. 작가들도 독자님의 꼼꼼한 공부 덕분에 다음 쇄에서 많은 오탈자와 내용 보완을 할 수 있게 되어 너무나 감사 드립니다.

문의 주신 내용은 strong_order로 수정되어야 합니다. 정오표에 반영해 놓도록 하겠습니다.
완독하시느라 정말 고생 많으셨습니다. 앞으로도 공부하시면서 궁금한 사항이 있으시면 언제든지 이곳에 질문 남겨주세요.

감사합니다.

**Comment by DesignMoon** [comment]
책을 쓴 저자 입장에서 완독해주신 독자가 있다는 건 너무나 감사한 마음이 듭니다. 내심 오늘은 독자님의 어떤 질문과 이슈가 올라올까 매일 기다려지기도 했습니다.

꾸준히 정진하시어 원하시는바 이루시길 기원드립니다.
앞으로도 공부하시다가 궁금한 점, 편하게 질문 남겨주세요.

다시한번 수고하셨고 감사드립니다.
