### ISSUE TITLE
챕터2 데이터 형식 질문

### ISSUE THREAD

**Issue by ssmjung** [mystous/DoItCPP#13]
안녕하십니까?

1. 42페이지 중간부분 오타 같습니다
 네임스페이스입닌다->네입스페이스입니다

2. 47페이지 wchar_t가  3byte로 되어 있는데 52페이지는 2byte로 되어있어서 어떤게 맞는지 질문드립니다

수고하십시오

**Comment by DesignMoon** [comment]
안녕하세요. 독자님
소중한 오타 제보 감사드립니다.

**1. 42p
~~ 정의된 네임스페이스입닌다. -> ~~ 정의된 네임스페이스입니다.**

**2. 47p
char32_t : 4byte
wchar_t : 2byte**

참고로 wchar_t의 크기는 시스템에 따라 다를 수 있습니다. 하지만 일반적으로 wchar_t는 최소한 2바이트 이상의 크기를 가집니다.

47페이지 표에서 크기 3이 들어갈 부분이 없었는데 일괄로 오타가 난 것 같습니다.
독자님 덕분에 정오표에 반영하도록 하겠습니다.

확인되셨다면 close 부탁드리며, 추가적인 질문이 있다면 언제든지 자유롭게 이슈 남겨주세요.
감사합니다!
