### ISSUE TITLE
챕터2 86page 그림2-7 문의

### ISSUE THREAD

**Issue by ssmjung** [mystous/DoItCPP#14]
안녕하십니까?
챕터2 86페이지 그림2-7에 왼쪽 시프트(<<)연산의 그림이 좀  잘못 된것 같네요
아래 비트의 시작위치가 왼쪽으로 한칸 이동해 있으며 화살표도 잘못표기되어 한칸씩 앞에 연결되어야 할것 같습니다
수고하십시오

**Comment by DesignMoon** [comment]
안녕하세요. 독자님
2-7 그림 << 연산의 화살표가 한칸씩 밀려서 표현되었네요.
언급주신대로 화살표가 한칸씩 앞으로 이동해서 연결되어야합니다.
이 부분도 정오표에 반영하도록 하겠습니다.
예리하게 체크해주셔서 정말 감사합니다.
이 메시지 보셨다면 close 부탁드릴께요!
