### ISSUE TITLE
챕터3 127페이지 구조체 질문

### ISSUE THREAD

**Issue by ssmjung** [mystous/DoItCPP#15]
안녕하십니까?
챕터3 127페이지 구조체 선언을 할때 
std::string name;
으로 선언하셨는데 
using namespace std; 가 
있는데 왜 구조체 선언할 때 
std::를 써 줘야 하는지 궁금합니다
수고하십시오

**Comment by DesignMoon** [comment]
안녕하세요, 독자님
오늘도 글 남겨주셔서 반갑습니다.

독자님께서 언급주신대로 127p 부분은 using namespace; 가 있어서 Person 구조체 내에서도 std:: 없이 string 변수를 선언해도 됩니다.

하지만 저는 125p 예시 부분 코드에서 보여드린 구조체를 그대로 사용했기 때문에 std:: 도 함께 딸려왔는데요,
설명 때 활용한 부분 코드를 그대로 활용해서 실습 예제 코드를 만드는 것이 독자님들께서 좀 더 이해하기 좋을 것 같아서 결정한 부분이라 봐주시면 좋을 것 같습니다.

충분히 이해가 되셨다면 close 부탁드리겠습니다.
항상 감사드립니다 :)
