### ISSUE TITLE
챕터5 177, 181페이지 오타

### ISSUE THREAD

**Issue by ssmjung** [mystous/DoItCPP#16]
안녕하세요?
중요한 내용은 아니지만 오타 같아서 글 남김니다

p177
맨 마지막줄 
cout<<"after throw 1"<<endl;   -> cout<<"after throw -1.0f"<<endl;

p181
throw -1.0f;
cout<<"after throw 1"<<endl;   ->     cout<<"after throw -1.0f"<<endl;

수고하십시오

**Comment by DesignMoon** [comment]
어서오세요, 독자님
이번에도 오타 제보 걈사드립니다.

예외발생시 그 아래 코드들은 실행되지 않습니다.
때문에 이해를 돕기 위한 더미코드 부분이라 예제 결과는 동일할겁니다.

하지만 독자님 덕분에 언급주신 부분까지 반영하여, 다음 인쇄시 더 완성도 있는 책에 한걸음 다가설 수 있을 것 같습니다.

이번에도 답변 확인하시면 close 부탁드릴께요
항상 감사드려요  :)
