### ISSUE TITLE
VScode로 공부해도 괜찮나요?

### ISSUE THREAD

**Issue by HjyunO** [mystous/DoItCPP#17]
교재는 VS로 강의를 하시는데 VScode로 공부해도 괜찮을까요?

**Comment by mystous** [comment]
독자님, 안녀하세요?

VSCode로도 실습 예제를 실행하시는데 문제는 없습니다.
모든 코드는 Standard C++ 규약으로 작성되었습니다.
그리고 대부분의 코드가 단일 파일로 이루어져 있기 때문에 실습하는데 큰 문제는 없습니다. (컴파일러 버전 주의)

다만, 제공되는 예제 파일이 VS 솔루션 파일이며, 몇몇 설정이 맞춰져 있어 VS Community 버전 또는 라이선스 버전 사용을 권합니다.
그리고 VSCode 설정 방법 및 관련된 오류는 저희가 질의 응답이 어려운 점은 양해 부탁 드립니다.

감사합니다.

ps. 추가 질문이 있으시면 쓰레드 이어서 작성해주실 바랍니다. 
      별도 질문이 없으시다면 Issue Close 처리 부탁 드립니다. :)
