### ISSUE TITLE
255p 질문

### ISSUE THREAD

**Issue by HjyunO** [mystous/DoItCPP#18]
안녕하세요 저자님. 책으로 잘 공부하고 있습니다.
다름이 아니라 255p 파라매터가 있는 생성자 부분 및 다른 예제 코드에서 클래스 내부에 함수를 정의할 때 세미콜론을 쓰시는 이유가 있으실까요? 세미콜론을 쓰지 않아도 컴파일이 잘 되어서 질문드립니다.

**Comment by mystous** [comment]
안녕하세요.

클래스 선언부에서 멤버 함수 선언, 정의를 모두 할 경우 함수 정의부의 } 뒷부분이는 ; 이 필요없습니다.
C++에서는 ; 사이가 구문으로 인식합니다. 그래서 한줄로 소스 코드를 만들어서 아스키 아트를 만들기도 합니다.
정의부 뒷 부분 ;은 빈칸 처럼 인식해서 컴파일이나 수행에 영향을 미치지 않습니다.

다만, 저는 다른 함수 선언과 일관적인 가독성을 위해 추가 해서 작성합니다.
독자님은 꼭 붙이시지 않아도 됩니다. :)
개정판에서는 공저자 선생님과 논의하여 조절여부를 결정하겠습니다.
세세한 부분 확인 질문 감사합니다.

추가 문의가 있다면 질문 추가해주시고요. 
없으시다면 Issue close 부탁드립니다.
