### ISSUE TITLE
C++ 교재 p74 관련 질문

### ISSUE THREAD

**Issue by cuesign** [mystous/DoItCPP#19]
Do it! C++ 완전 정복
https://www.easyspub.co.kr/20_Menu/BookView/662/PUB

상기 교재의 p74에 있는 표 2-11을 Cpp 코드로 만들어서
모니터에 출력되도록 하려면 cout 말고 어떤 명령어를 사용해야 하나요?

cout으로 하니까 오류가 발생해서요.

**Comment by mystous** [comment]
독자님, 안녕하세요?

문의 주신 내용에서 일반문자, 와이드 문자까지는 문제 없이 출력 되셨을 것 같습니다.
```
std::string str("Hello");
std::wstring str3(L"Hello");
```

문제는 UTF-8문자, UTF-16문자, UTF-32문자에서 발생하셨을꺼에요.
UTF-8의 경우 std::cout이 아닌 std::wcout을 사용하면 출력할 수 있습니다.
`std::wcout << str3 << std::endl;`

하지만 UTF-16, 32 문자의 경우 std::wcout으로도 출력이 안됩니다. 이때는 UTF-16, 32 문자를 cout이나 wcout이 출력이 가능한 형식으로 변경해야 합니다. 조금 복잡하지만 예제로 소개 하겠습니다. 책에 내용이 충분하지 못한 부분은 2쇄에서 보강하도록 하겠습니다.

C++14 버전으로 컴파일 되는 소스 입니다.
```
#include <iostream>
#include <locale>
#include <codecvt>

int main()
{
  std::wstring_convert<std::codecvt_utf8<char16_t>, char16_t> converter_16;
  std::wstring_convert<std::codecvt_utf8<char32_t>, char32_t> converter_32;
  std::string str("Hello");
  std::wstring str3(L"Hello");
  std::string str2(u8"Hello");
  std::u16string str4(u"Hello");
  std::u32string str5(U"Hello");

  std::cout << str << std::endl;
  std::wcout << str3 << std::endl;
  std::cout << str2 << std::endl;
  std::cout << converter_16.to_bytes(str4) << std::endl;
  std::cout << converter_32.to_bytes(str5) << std::endl;

  return 0;
}

```

추가적인 질문이 있으시면 알려주시고, 이해가 충분히 되셨다면 Issue Close도 부탁 드립니다.

감사합니다.

**Comment by cuesign** [comment]
답변 감사합니다.
