### ISSUE TITLE
챕터2 55p 정수 표현 범위 질문

### ISSUE THREAD

**Issue by JangIn-40** [mystous/DoItCPP#2]
안녕하세요 저자님 계속 책 잘 읽고 있습니다.
다름이 아니라 정수 표현 범위를 수학 공식으로 표현했을때 unsigned범위를 책에서는 2^(n-1)-1이라 표현 돼있는데 2^(n)-1이 아닌가 싶어 문의드립니다.

**Comment by DesignMoon** [comment]
책의 오탈부분을 정확하게 짚어주셨습니다.
조판 과정에서 지수 표현에 살짝 오류가 있었네요.

독자님께서 언급하신 부분이 맞으며,
n비트(n-bit)의 signed(부호 있는)와 unsigned(부호 없는) 범위는 다음과 같습니다.

signed 범위: -2^(n-1) ~ 2^(n-1) - 1
unsigned 범위: 범위: 0 ~ 2^n - 1

덕분에 정오표에 반영하도록 하겠습니다.
추가로 오타 부분이 발견되면 언제든지 짚어주세요. :)
