### ISSUE TITLE
질문 - 교재 p191의 실행결과

### ISSUE THREAD

**Issue by cuesign** [mystous/DoItCPP#20]
![교재 p191 실행결과](https://github.com/user-attachments/assets/717eb0f7-4f56-472e-a7fe-a3a717133866)

제가 실행한 교재 p191의 실행결과는 상기 캡처 이미지와 같습니다. 

교재  p191에 기재된 결과와는 다르게 나타나내요. 

이에 대한 설명 부탁드립니다.

**Comment by mystous** [comment]
Issue #21 의 내용과 이어져서 답변드릴 수 있어서 이 Issue는 Close 하도록 하겠습니다.

**Comment by mystous** [comment]
독자님, 안녕하세요?

교재에 있는 내용은 컴파일 시 발생하는 컴파일 오류 입니다.
![image](https://github.com/user-attachments/assets/aea057b3-9836-4ee3-85d6-ba0d12884167)

그리고 실행을 하면 독자님이 보신 오류창이 뜹니다.

192페이지의 첫번째 문단의 첫문장
"이 코드를 컴파일 하면 경고는 발생하지만 어쨌든 실행 파일은 만들어집니다."
   => 위 스크린 캡쳐의 경고가 발생함
   
첫번째 문단의 세번째 줄
"하지만 실행해 보면 런타임 오류 메시지가 발생하며 프로그램은 강제로 종료됩니다."
   => 독자님의 캡쳐하신 오류 발생
   
 다음 쇄에서는 이해가 쉽도록 그림이나 내용 수정을 고려해 보겠습니다.
 
 내용 확인 되셨으면 Issue Close 부탁 드리며, 
 추가적으로 궁금하신 내용이나 이해가 안되신 부분이 있다면 추가 질문 부탁 드립니다.

감사합니다.
