### ISSUE TITLE
질문 - 교재 p192의 실행결과

### ISSUE THREAD

**Issue by cuesign** [mystous/DoItCPP#21]
교재 p192의 set_terminate.cpp 파일에 보면, 
 --> 교재 p192에는#include <cstdlib> 라고 기재되어 있는데, 
 --> 실제 set_terminate.cpp 파일 내부에서는 #include <exception>  으로 기재되어 있습니다. 
교재에 제공되는 소스코와 교재 p192의 기재사항이 차이가 있는데 괜찮은 건가요?

--------------------------------------------------------------------------------------------

![교재 p192 실행결과(1-6)](https://github.com/user-attachments/assets/09654f21-7ba6-4409-930a-2bd08ea26cbc)
![교재 p192 실행결과(2-6)](https://github.com/user-attachments/assets/1a97c73c-7d0c-43dd-9100-d5f9633ba70e)
![교재 p192 실행결과(3-6)](https://github.com/user-attachments/assets/c48927a0-82e6-4d89-8860-fcfb51f98d52)
![교재 p192 실행결과(4-6)](https://github.com/user-attachments/assets/c707d579-790a-4d12-a870-47777e6484a6)
![교재 p192 실행결과(5-6)](https://github.com/user-attachments/assets/69bd389c-4b29-4d2c-9ce3-927958629b00)
![교재 p192 실행결과(6-6)](https://github.com/user-attachments/assets/70b704d6-e174-481e-bd16-1a4002c3a033)

위 캡쳐 이미지 사진 결과에서 보면 p192의 실행결과가 
Visual Studio에서 "로컬 Windows 디버거" 버튼을 눌러서 실행할 때의 결과와
"디버그하지 않고 시작" 버튼을 눌러서 실행할 때와의 결과가 다르게 나오는데,
왜 그런지 설명 부탁드립니다.

**Comment by mystous** [comment]
안녕하세요? 독자님, 

질문이 여러개여서 별도의 코멘트로 답변 드리겠습니다.

Q.
교재 p192의 set_terminate.cpp 파일에 보면,
--> 교재 p192에는#include <cstdlib>라고 기재되어 있는데,
--> 실제 set_terminate.cpp 파일 내부에서는 #include <exception>으로 기재되어 있습니다.

  => 질문주신 내용에 헤더 파일의 이름이 없어 교제와 예제 프로젝트를 보고 제가 수정했습니다. 혹 다른 내용이면 알려주세요.

A.
교재에 오타 입니다. 실제로 <cstdlib>, <exception> 모두 없어도 정상 동작합니다.
@DesignMoon 작가님이 한 번 더 확인해 주시고 정오표에 추가 하도록 하겠습니다.

**Comment by mystous** [comment]
스크린 캡쳐해주신 부분은 Visual Studio 디버거에서 처리되지 않은 예외를 발견하여 강제 종료를 하여 더 이상 후 처리가 되지 않은 것 같습니다. 상세한 내용은 @DesignMoon 작가님이 자세히 확인해서 답변 드리겠습니다.

**Comment by DesignMoon** [comment]
안녕하세요. 독자님

남겨주신 질문에 **#inlcude** 키워드만 보여서, 독자님의 질문을 다시 한번 더 확인해봅니다.

교재 192p에서 **#include &lt;cstdlib&gt;** 로 기재되어 있는데, 실제 소스 "set_terminate.cpp"에서는 **#include &lt;exception&gt;** 로 선언되어 있다는 질문이시죠?

답을 드리면 교재에 있는 것은 오타이고, 실제 소스  "set_terminate.cpp" 에 있는 **#include &lt;exception&gt;** 헤더가 맞습니다.

소스를 옮기는 편집과정에서 실수가 발생한 것 같습니다.
해당 부분은 정오표에 반영하도록 하겠습니다.
<br><br>

추가로 질문 주신 **"로컬 Windows 디버거" 와 "디버그하지 않고 시작" 의 차이는?** 에 대해서도 답변을 드립니다.

1. 로컬 Windows 디버거 (단축키 : F5)
: 중단점 설정, 단계별 실행, 변수 검사, 호출 스택 추적 등의 디버깅을 시작한다는 의미입니다.
  때문에 디버거가 활성화되어 있어 프로그램의 예외나 오류가 발생하면 디버거가 이를 감지하고 중단하지요.
  그래서 첨부 주신 첫번째 스크린 샷 처럼 예외가 처리되지 않음을 확인할 수 있었던 것입니다.

2. 디버그하지 않고 시작 (단축키 : Ctrl+F5):
: 디버거가 프로그램에 첨부되지 않습니다.
  그 의미는 디버깅 기능을 사용할 수 없으며, 프로그램이 일반 실행 모드로 실행된다는 것이지요.
  예외나 오류가 발생하면 프로그램이 디버거 없이 기본 예외 처리 루틴에 따라 종료되거나 계속 실행됩니다.
  때문에 마지막 스크인 샷 처럼 별도의 알림없이 프로그램이 종료되어 버린 것입니다.

* 추가로 "계속" 버튼에 대해서도 알려드릴께요.
  디버깅 중 '계속' 버튼의 의미는 현재 디버그 모드에서 일시 중지된 프로그램의 실행을 다시 시작하는 것입니다.
  예외가 발생하여 프로그램이 일시 중지된 상태에서 '계속' 버튼을 누르면, 디버거가 예외를 처리하고 프로그램 실행을 계속합니다.
단, 처리되지 않은 예외일 경우 프로그램이 종료될 수 있습니다.

<br><br>
위의 답변이 충분하셨다면 해당 이슈는 close 부탁드립니다.
그리고 좋은 책이 될 수 있도록 오타 제보에 대해서도 다시 한번 감사드립니다.

앞으로 C++ 언어의 진수 "객체지향 프로그래밍" 에 대해서도 계속 공부하실텐데요,
다소 생소하고 어렵더라도 끝까지 공부하시길 응원드립니다.

책을 보시다가 이상한 부분은 언제든지 물어봐주세요.
그럼 완독 꼭 부탁드릴께요!
