### ISSUE TITLE
교재 p223의 그림 6-12

### ISSUE THREAD

**Issue by cuesign** [mystous/DoItCPP#23]
![교재 p223](https://github.com/user-attachments/assets/9f81317b-9a8e-4b03-996f-3d4abd9c2ed9)

교재 p223의 그림 6-12에 보면 각 상자안에 -와 +로 표시된 부분이 있는데, 

어떤 원칙에 의거해서 어떨 때는 -를, 어떨 때는 + 를 사용하는 건가요?

**Comment by mystous** [comment]
독자님, 안녕하세요?

클래스 다이어 그램에서 + 는 클래스 외부에서 접근이 가능한 'public' 접근제어자가 사용된 경우이고
-는 외부에서 접근이 불가능한 'private' 접근제어자가 사용된 경우입니다.

현재 공부하시는 교재 뒷쪽 231페이지에도 설명이 나와 있으니 참고하시면 됩니다.
접근제어자는 뒷쪽에 상세히 설명되어 있습니다.

감사합니다.
