### ISSUE TITLE
교재 309페이지 실행 오류

### ISSUE THREAD

**Issue by waldong-wintering** [mystous/DoItCPP#24]
![c++ 309](https://github.com/user-attachments/assets/6a988b81-ba2c-4534-9b51-6377d69e72df)

코드 작성 후 이렇게 나오는데 제가 무엇을 놓치고 있는 것인지 잘 모르겠습니다.

**Comment by mystous** [comment]
독자님, 안녕하세요?

화면캡쳐만으로 저희도 오류 내용을 파악할 수 없습니다.
소스 코드 전체를 복사 & 붙여넣기 해주세요.

308~309페이지에 걸치 예제는 생략된 부분도 있습니다. 이 부분은 예제 파일을 다운로드 받아서 확인해주세요.

**Comment by mystous** [comment]
독자님, 안녕하세요?

오류가 발생한 직접 작성하신 소스 코드 쓰레드에 넣어 주시면 문제점 파악해서 설명 드리겠습니다.
별도의 답변이 없으신 상태로 Issue가 오래 Open되어 있으면(1주) 이 이슈는 Close 하도록 하겠습니다.
