### ISSUE TITLE
교재 p344~348의 begin( ), advance( ) 함수 의미?

### ISSUE THREAD

**Issue by cuesign** [mystous/DoItCPP#28]
교재 p344~348의 
get_monster(const int terrain_type, int index) 멤버함수 안에 보면

begin( ), advance( ) 함수가 있는데, 의미 설명 부탁드립니다.

**Comment by mystous** [comment]
안녕하세요?

질문 주신 함수 모두 list 클래스 멤버 변수 입니다. 
우선 간략히 설명 드리고 상세 내용 확인할 수 있는 블로그 링크를 안내 드리도록 하겠습니다.

list 클래스는 배열과 유사하지만 크기를 자유롭게 사용할 수 있다는 장점이 있습니다. 
12장에서 배울 컨테이너의 개념입니다. 상세한 내용은 12장에서 공부하시면 되고, 지금 진도에서는
배열대신 메모리 관리가 편한 클래스로 생각하시면 됩니다.
대신 배열 처럼 []로 접근할 수도 있지만, 메모리 관리 (추가, 삭제가 반복이 되면서) 때문에 
begin(), advance() 함수를 사용합니다. begin()은 list의 가장 처음을 반환하는 함수 있며 반환 형식은 iterator 입니다. (뒷장에서 상세히 배웁니다.)
advance()는 배열의 [] 처럼 특정 인덱스에 접근할 수 있는 함수 입니다. 이때 인자로 list의 처음을 알려 줘야 하는 때 
그때 begin()으로 반환 받은 iterator를 넣어 줍니다.

지금 진도에서는 list는 동적으로 크기가 늘어나고 메모리 관리가 필요 없는 배열과 유사한 클래스이다.
대신 특정 인덱스의 데이터를 가져 올때는 begin()과 advance() 함수를 사용한다라고 이해하시면 됩니다.

구글링 해도 많은 자료가 나오지만 제가 찾은 링크 두개 알려 드립니다.

begin 및 list 클래스 멤버 함수 설명(https://twpower.github.io/78-how-to-use-list-in-cpp) 
advance() 멤버 함수 설명(https://zepeh.tistory.com/124)

감사합니다.
