### ISSUE TITLE
교재 p358의 dis와 gen

### ISSUE THREAD

**Issue by cuesign** [mystous/DoItCPP#29]
교재 p358에 보면, main( ) 함수 안에

target_player_dummy.set_location(dis(gen), dis(gen));

라는 내용이 있는데, 여기서 dis와 gen이 뭔지 질문합니다. 

## gen의 경우, 
mt19937 gen(rd()); 라는 메소드 같은데, 

target_player_dummy.set_location(dis(gen), dis(gen)); 라는 문장에서는
마치 변수 처럼 사용된 것 같아서, gen이 변수인지 함수인지 구별이 안되서 질문합니다. 

## dis의 경우, 
uniform_int_distribution<int> dis(0, 99); 라는 전역 멤버함수로 판단되는데, 
확률/통계 관련해서 0부터 99까지의 균일분포 관련하여 난수를 발생시키는 함수인가요?

**Comment by mystous** [comment]
안녕하세요?

**1) gen**

mt19937은 using으로 별칭된 클래스입니다. 
```cpp
_EXPORT_STD using mt19937 = mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 0x9908b0df, 11, 0xffffffff, 7,
    0x9d2c5680, 15, 0xefc60000, 18, 1812433253>;
```
 
따라서 gen(rd());은 rd(역시 클래스) 객체를 시드값으로 하는 난수 스퀀스(여러개의)를 생성하는 객체를 생성합니다.
std::cout << gen << std::endl; 로 출력해 보면 난수 스퀀스가 보여집니다.

그런데  gen은 객체 이름이고 함수 호출을 하지 않았는데 어떻게 난수 시퀀스가 생성이 될까요?
비밀은 클래스에서 정의한 operator() 함수 입니다. 이 함수는 gen 처럼 객체만 코드에 있을때 동작하는 함수의 정의 입니다.
 mersenne_twister_engine는 operator()를 통해서 난수 시퀀스를 생성하는 함수가 정의 되어 있습니다.

**2) dis**
uniform_int_distribution dis(0, 99)는 0부터 99까지의 숫자를  균등분포를 통해서 하나 반환 하는 함수 입니다.
이 함수는 수십번 반복해서 호출 한 후 반환값으 통계를 보면 균등 분포로 보여 집니다.
아래 그래프는 위 과장을 ChatGPT를 통해서 10,000번 반복한 결과 입니다.
![image](https://github.com/user-attachments/assets/57439a9a-6b47-4847-af71-bda95f47a1c8)

100,000번일때는 좀 더 균일한 분포를 보여 줍니다.
![image](https://github.com/user-attachments/assets/f9cd2244-4d2a-4f98-93b1-dd66ff354269)

설명이 부족하거나 이해가 어려운 부분이 있다면 다시 한 번 질문 주시면 확인 후 답변 드리도록 하겠습니다.

감사합니다.
