### ISSUE TITLE
챕터2 93p 연산자 우선순위, 챕터3 109p 배열원소의 주소와 포인터 연산의 결과 비교 질문

### ISSUE THREAD

**Issue by JangIn-40** [mystous/DoItCPP#3]
안녕하세요 저자님! 오늘도 잘 읽고 있습니다.
다름이 아니라 93p 실습에서 세번째 주석에 곰셈 먼저 연산이 아닌 곱셈 먼저 연산이지 않나 싶습니다. 그리고 이건 확실하진 않지만 109p 실행결과에서 lotto[0] Addrees와 (lotto + 0) Address의 주소가 서로 달라서 질문드립니다. 앞페이지에서 배열의 메모리 상태가 각 원소마다 붙어있다고 되어있는데 lotto[0] Address만 이상한 것 같아 질문드립니다! 그리고 혹시 오탈자가 맞다면 바로 아래에 있는 표3-1의 0번인덱스의 주소와 포인터 연산의 첫번째 주소도 확인 부탁드립니다. 감사합니다!

**Comment by DesignMoon** [comment]
오 독자님, 오탈자 찾아주셨네요!

93p
곰셈 -> 곱셈 이 맞습니다.

109p
&lotto[0], lotto + 0
둘 다 모두 000000DFE48FF9E0 입니다.

꼼꼼히 봐주셔서 감사합니다 :)
