### ISSUE TITLE
교재 p364의 실행결과 관련 - create_terrain() 함수의 연관성

### ISSUE THREAD

**Issue by cuesign** [mystous/DoItCPP#30]
교재 p364 관련한 실행결과는

![p364의 실행결과-1](https://github.com/user-attachments/assets/831c29ca-0f3b-442a-ab94-8004fc9fbce3)

위 사진에 보시면 빨간색으로 표시된 부분이 매번 실행시 달라지는데, 
create_terrain() 함수와의 연관된 것인지를 질문합니다. 

void monster_factory::create_terrain() {
  terrain_inst[0] = new forest_terrain();
  terrain_inst[1] = new cyber_terrain();
  terrain_inst[2] = new urban_terrain();

  for (auto object : terrain_inst) {
    object->set_start_location(dis(gen), dis(gen));
    object->set_end_location(dis(gen), dis(gen));
  }
}

create_terrain() 함수를 보면, 

![p364의 terrain_inst](https://github.com/user-attachments/assets/d1863947-8d0e-49f7-9664-3d387967a660)

위와 같을 텐데요, 

따라서 관련 실행결과는 아래와 같이 일정하게 나와야 할 것 같은데, 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
Monster A를 숲에 배치 합니다.
몬스터A가 숲에서는 힘이 더 강해 집니다.

모든 종류의 Monster를 사이버 공간에 배치 합니다.
모든 몬스터가 사이버 공간에서는 속도가 빨라 집니다.

Monster B, C를 도심에 배치 합니다.
Monster C는 도심에 힘이 강해 집니다.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

그럼에도 불구하고, 교재 p364 관련한 실행결과는 왜 매번 순서가 뒤섞여서
결과가 나오는지 잘 이해가 안되서 질문드렸습니다. 답변해 주시면 감사하겠습니다.

**Comment by mystous** [comment]
안녕하세요?

main 함수의 흐름을 보시면,  플레이어를 배치한 후 
1. 지형을 생성하고 - create_terrain
2. 몬스터를 생성합니다. - initialize_monster

create_terrain()은 질문 주신 석처럼 terrin_inst에 숲, 사이버 공간, 도심 으로 생성이 됩니다.
이후 몬스터를 생성하고 배치 할 때 랜덤하게 배치가 됩니다. 

```cpp
void monster_factory::initialize_monster() {
  create_monster(forest_terrain_type, 2);
  create_monster(cyber_terrain_type, 3);
  create_monster(urban_terrain_type, 1);
}

void monster_factory::create_monster(const int terrain_type, int count) {
  monster* mon = nullptr;

  for (int i = 0; i < count; ++i) {
    mon = monster_factory::create_monster(terrain_type, terrain_inst[select(gen)]);
    mon->set_location(dis(gen), dis(gen));
  }
}

monster* monster_factory::create_monster(const int terrain_type, terrain* terrain_inst) {
  monster* new_mon = nullptr;
  switch (terrain_type) {
  case forest_terrain_type:
    new_mon = new monster_a();
    break;
  case cyber_terrain_type:
    new_mon = new monster_b();
    break;
  case urban_terrain_type:
    new_mon = new monster_c();
    break;
  }

  // 종류에 상관없이 monster 클래스로 업캐스팅 하여 동일한 흐름 실행
  terrain_inst->allocate_monster(new_mon);
  terrain_inst->bost_monster(new_mon);
  mon_list.push_back(new_mon);
  mon_count++;
  return new_mon;
}
```

호출 순서에 맞게 initialize_monster(), create_monster(const int terrain_type, int count), create_monster(const int terrain_type, terrain* terrain_inst)로 배치 하였습니다.
뒷쪽 create_monster는 오버로딩 되어 있습니다.

initialize_monster에서는 몬스터 종류를 A, B, C로 각각 2, 3, 1 마리씩 만듭니다. 세번째 함수에서 terrain_type에 맞는 몬스터를 생성하는 것을 확인할 수 있습니다.

질문 주신 랜던성은 두번 째 create_monster에서 발생합니다. 오버로딩된 세번째 create_monster를 호출 할 때 생성될 몬서터의 지형 특성(A, B, C를 결저)과 이 몬스터들이 위치하게 될 지형을 두번 째로 인자로 넣습니다. 
```cpp
mon = monster_factory::create_monster(terrain_type, terrain_inst[select(gen)]);
```
두 번째 인자를 보시면 terrain_inst의 0, 1, 2 인덱스를 select(gen)으로 랜덤하게 선택을 하게 됩니다. 
그래서, 몬스터들 종류별로 항상 같은 지형에 배치되는게 아니라 다른 지형에 배치 됩니다.

그리고 각 지형별로 배치하는 몬스터의 종류가 달라서 출력되는 문장의 총 숫자도 바뀝니다. 
소스 코드가 조금 복잡하고 다형성이 강조되다 보니 흐름을 파악하기 어려울 수 있을 것 같습니다.

아직 이해가 부족한 부분이나 어려운 부분이 있다면 알려주세요.

감사합니다.

**Comment by cuesign** [comment]
상기에 설명해 주신 내용은 이해했습니다. 

그런데 맨 마지막에 있는 
mon = monster_factory::create_monster(terrain_type, terrain_inst[select(gen)]);
에서

select(gen)에서 gen은

mt19937 gen(rd()); 으로 보이는데, 

select(gen)의 실행결과가 왜 0, 1, 2 중의 하나로만 나오는지 궁금합니다. 

그리고 select() 함수의 의미도 설명 부탁드립니다.

**Comment by mystous** [comment]
select()은 C++ 컴파일러나 라이브러리에서 제공하는 함수가 아닙니다. 
해당 소스 코드의 상부를 살펴 보겠습니다.

```cpp
uniform_int_distribution<int> dis(0, 99);
uniform_int_distribution<int> select(0, 2);
```

https://github.com/mystous/DoItCPP/issues/29 
이 질문/대답을 참고하면 dis에 대한 설명이 있습니다. select은 dis와 동일하게 uniform_int_distribution의 객체 입니다.
차이점은 dis는 0부터 99까지의 정수를 균등 분포가 이루도록 반환합니다. select는 인자값에서 알 수 있듯이 0, 1, 2를 균등 분포에 따르도록 반환합니다. 그리고 시드로 난스 시퀀스를 입력 받습니다. (gen)
