### ISSUE TITLE
교재 p437의 back_inserter( )

### ISSUE THREAD

**Issue by cuesign** [mystous/DoItCPP#32]
교재 p437의 back_inserter( )는 멤버함수 인가요? 클래스 인가요?

**Comment by DesignMoon** [comment]
안녕하세요. 독자님

객체지향 개념 부분을 넘고 이제 표준라이브러리로 오셨군요.
포기하지 않고 읽어주셔서 감사합니다.

질문 주신 것에 대해 답변 드리겠습니다.

back_inserter는 표준 라이브러리에서 제공되는 어댑터 함수로, 특정 컨테이너의 끝에 원소를 삽입할 수 있는 반복자를 반환합니다.

책 437p 페이지 코드를 기준으로 설명하면, back_inserter(to_vector)는 to_vector의 끝에 원소를 추가할 수 있는 반복자를 반환합니다.

```cpp
copy(from_vector.begin(), from_vector.end(), back_inserter(to_vector)); 
```

즉, 책에 등장하는 상기 코드는 from_vector의 첫 번째 원소부터 마지막 원소까지 순서대로 to_vector의 끝에 복사하게 됩니다.
back_inserter는 보통 std::copy와 같은 알고리즘과 함께 사용되니 셋트로 익혀두시면 좋습니다. :)

답변에 충분했다면 close 부탁드립니다.
