### ISSUE TITLE
교재 p540, p541 

### ISSUE THREAD

**Issue by cuesign** [mystous/DoItCPP#36]
이지스퍼블리싱 출판사에서 제공하는 교재 본문의
소스코드들 중에서 교재 p540, p541의 소스코드들을
찾을 수가 없습니다. 원래 포함이 안된 건가요?

**Comment by mystous** [comment]
독자님, 안녕하세요?

책의 소스 코드 안내가 오기되어 있네요.

540 페이지 예제는
ch14/normal_ptr/normal_ptr.cpp 이고

541 페이지 예제는
ch14/unique_ptr/unique_ptr.cpp 입니다.

정오표에 기입하도록 하겠습니다.
불편을 드려서 죄송합니다.

**Comment by mystous** [comment]
@cuesign 독자님, 안녕하세요?

더 이상 추가 질문이 없으시면 다음주 초에 이 이슈는 Close 하도록 하겠습니다.

감사합니다.
