### ISSUE TITLE
교재 10장 p382의 템플릿 특수화 관련 질문

### ISSUE THREAD

**Issue by cuesign** [mystous/DoItCPP#39]
교재 10장 p382의 소스코드에서 

#include <iostream>
#include <string>

using namespace std;

template <typename K>
K data_sum(K operand1, K operand2) {
  return operand1 + operand2;
}

template <>
double data_sum(double operand1, double operand2) {
  return  (int)operand1 + (int)operand2;
}

/*
template <>
int data_sum(int operand1, double operand2) {
	return  operand1 + (int)operand2;
}
*/

int main() {
  int data1 = 3, data2 = 5;
  double data3 = 4.5, data4 = 8.9;
  string data5 = "Hello, ", data6 = "World!";

  cout << "정수형 데이터 합: " << data_sum(data1, data2) << endl;
  cout << "실수형 데이터 합: " << data_sum(data3, data4) << endl;
  cout << "문자열 데이터 합: " << data_sum(data5, data6) << endl;
  // cout << "문자열 데이터 합: " << data_sum(data1, data4) << endl;
  return 0;
}

상기에 주석 처리된 

template <>
int data_sum(int operand1, double operand2) {
	return  operand1 + (int)operand2;
}

부분과

cout << "문자열 데이터 합: " << data_sum(data1, data4) << endl;
부분을 실행시 오류가 납니다. 

C++ 에서 템플릿 이용시 매개변수의 데이터 타입을 (예를 들어 매개변수 2개를 이용한다고 했을 때)
하나의 매개변수는  int로,  또다른 매개변수는  double로 서로 다른 데이터타입으로 하는 것이
가능한가요? 불가능한가요?

그리고 만약 가능하게 하는 다른 대안적 방법이 있다면 알려주시면 감사하겠습니다.

**Comment by mystous** [comment]
@cuesign 독자님, 안녕하세요?

어려운 템플릿 장을 공부 하고 계시군요! 좋은 질문 주셔서 감사합니다.

질문 주신 형태의 호출이나 특수화는 오류가 발생합니다. 우선 특수화를 하지 않고 템플릿 함수를 호출 할때에는
함수 템플릿의 템플릿 매개변수가 typename K 하나만 선언되었기 때문에 오류가 발생합니다.

독자님이 주석 처리하신 함수역시 오류가 발생합니다.
템플릿 특수화는 템플릿 함수가 동작할 때 특정 템플릿 매개변수 형식에 대해서 별도의 처리를 규정하는 것입니다.
그래서 원래 템플릿의 형식을 벗어나서 템플릿을 정의 할 수 없습니다. 
아래와 같은 오류가 발생하는 원인입니다.
![image](https://github.com/user-attachments/assets/80da0a3c-5156-4145-a346-3e3d6f2239c4)

그래서 질문 주신 형식으로 템플릿 함수가 호출이 되게 하려면 템플릿 매개변수를 2개 선언해야 합니다.
아래 예제는 템플릿 매개변수를 2개를 가지는 함수 템플릿을 오버라이딩 한 예시입니다.
```cpp
#include <iostream>
#include <string>

using namespace std;

template <typename T>
T data_sum(T operand1, T operand2) {
  return operand1 + operand2;
}

template <typename T, typename T2>
T2 data_sum(T operand1, T2 operand2) {
  return (T2)operand1 + operand2;
}

template <>
double data_sum(double operand1, double operand2) {
  return  (int)operand1 + (int)operand2;
}

int main() {
  int data1 = 3, data2 = 5;
  double data3 = 4.5, data4 = 8.9;
  string data5 = "Hello, ", data6 = "World!";

  cout << "정수형 데이터 합: " << data_sum(data1, data2) << endl;
  cout << "실수형 데이터 합: " << data_sum(data3, data4) << endl;
  cout << "문자열 데이터 합: " << data_sum(data5, data6) << endl;

  cout << "정수형과 실수형 데이터 합: " << data_sum(data1, data4) << endl;

  return 0;
}
```

결과는 다음과 같이 출력 됩니다.
```
정수형 데이터 합: 8
실수형 데이터 합: 12
문자열 데이터 합: Hello, World!
정수형과 실수형 데이터 합: 11.9
```

템플릿 매개변수가 2개 사용된 함수를 특수화 하는 예제도 추가해 보겠습니다.
방금 정의한 함수는 두번째 인자가 더 표현 범위가 크다가 가정하고 형변환을 두 번째 인자에 맞췄습니다.

템플릿 특수화를 통해서 int 형식으로 double을 형변환 해보도록 하겠습니다.
이때 방금 정의한 함수 템플릿을 지우면 안됩니다.  특수화는 원래의 템플릿이 존재 하고 그 중 템플릿 매개변수가 특정한 경우 에 동작하는 함수이기 때문입니다.
```cpp
#include <iostream>
#include <string>

using namespace std;

template <typename T>
T data_sum(T operand1, T operand2) {
  return operand1 + operand2;
}

template <typename T, typename T2>
T2 data_sum(T operand1, T2 operand2) {
  return (T2)operand1 + operand2;
}

template <>
double data_sum(int operand1, double operand2) {
  return  operand1 + (int)operand2;
}

template <>
double data_sum(double operand1, double operand2) {
  return  (int)operand1 + (int)operand2;
}

int main() {
  int data1 = 3, data2 = 5;
  double data3 = 4.5, data4 = 8.9;
  string data5 = "Hello, ", data6 = "World!";

  cout << "정수형 데이터 합: " << data_sum(data1, data2) << endl;
  cout << "실수형 데이터 합: " << data_sum(data3, data4) << endl;
  cout << "문자열 데이터 합: " << data_sum(data5, data6) << endl;

  cout << "정수형과 실수형 데이터 합: " << data_sum(data1, data4) << endl;

  return 0;
}
```

이번에는 정수형으로 형변환이 되어서 출력되는 것을 확인하실 수 있습니다.

```
정수형 데이터 합: 8
실수형 데이터 합: 12
문자열 데이터 합: Hello, World!
정수형과 실수형 데이터 합: 11
```

다시 한 번 정리 하자면, 템플릿 특수화는 템플릿 매개변수의 숫자가 일치하는 함수 템플릿(또는 클래스 템플릿)이 있어야 합니다.
두 개의 템플릿 매개변수가 사용되기 위해서는 템플릿 매개변수에 맞는 함수 템플릿이 정의되어 있어야 합니다.

내용 읽어 보시고 추가 질문이 있으시면 추가 질문 주세요.
만약 설명이 충분하다고 생각하시면 Issue Close 부탁 드립니다.

감사합니다.
