### ISSUE TITLE
챕터 4 165p do~while 반복문 질문

### ISSUE THREAD

**Issue by JangIn-40** [mystous/DoItCPP#4]
안녕하세요 저자님! 오늘도 찾아왔습니다.
다름이 아니라 그림 4-7에서 do~while문 동작 방식에 do(조건식)이라 되어있는데 do에서는 따로 조건식이 없어야 할 것 같아 문의드립니다. 감사합니다!

**Comment by DesignMoon** [comment]
네 잘 짚어주셨습니다.
해당 그림에서
do (조건식) 가 아니라 그냥 do 가 맞습니다.
