### ISSUE TITLE
챕터6 218p adaptive_cruise_modeling 질문

### ISSUE THREAD

**Issue by JangIn-40** [mystous/DoItCPP#5]
안녕하세요. 저자님 책 잘 읽고 있습니다!
이번에는 깃허브 소스 코드 질문입니다. 6장 adaptive_cruise_modeling 깃허브소스코드에서는 43, 44줄 elec_engine클래스에서 { cout << "increasing_piston_speed" << endl; }; , { cout << "decreasing_piston_speed" << endl; }; 가 깃허브 소스 코드에는 없고 책에서는 있습니다. 깃허브에서 7장 소스코드 갱신이라고 되어있던데 제가 아직 7장까진 진도를 나가진 않아서 갱신사실을 모르는 것일수도 있습니다. 그리고 116, 117줄에서 깃허브소스코드에서는 전처리 지시자가 없지만 책에서는 전처리 지시자가 있습니다. 추가적으로 실습을 진행중 에러를 만났는데 
![캡처](https://github.com/mystous/DoItCPP/assets/156999923/28d0a382-bbe7-482a-a04c-5d11965b4f40)
아무리 찾아도 책과 다른 점을 못찾아 main()함수를 다시 따라쳤습니다. 그런데 이번에는 정상작동을 해서 이게 무슨 버그인지 전혀 모르겠습니다.. 바뀐게 main()함수만 다시 따라친건데 혹시 왜 그런지 알고 계실까요? ㅠㅠ...

**Comment by mystous** [comment]
JangIn-40 독자님, 안녕하세요?

6장 adaptive_cruise_modeling 예제는 마지막 편집 마무리 과정에서 작업한 내용이
책에는 적용되고 예제 소스코드에는 적용되지 않았네요. 예제 소스 코드 업데이트 하였습니다.

올려 주신 오류는 180라인에서 엔터를 한 번 더 입력하시고 컴파일 하면 아마도 해결되지 않을까 합니다.
참고: https://copynull.tistory.com/245

이후 오류가 나는 구문은 그림보다는 소스 자체를 올려주시면 문제를 봐드리는데 더 빠르게 도움을 드릴수 있습니다.

내용 확인하시고 이슈 Close 부탁 드리겠습니다.

감사합니다.
