### ISSUE TITLE
챕터6 223p 실습예제 추가질문, 챕터7 246p 오버라이딩 질문 

### ISSUE THREAD

**Issue by JangIn-40** [mystous/DoItCPP#6]
안녕하세요 저자님 책 잘 읽고 있습니다.
다름이 아니라 218p~ 223p 실습예제의 실행결과가 없는데 의도하신건지 아닌지 몰라서 문의드립니다. 그리고 246p 본문에서 두번째줄에 attack_special(palyer)라고 되어있는데 attack_special(player)가 되야할것 같습니다. 추가적으로 262p, 267p의 monster_b클래스의  location을 유니폼 초기화한 것에서 0이 하나는 빗금이 쳐져있고 하나는 빗금이 안쳐져있는데 두개가 다른것인가 궁금하여 문의드립니다. 감사합니다.

**Comment by mystous** [comment]
@JangIn-40 독자님, 안녕하세요?

오늘도 꼼꼼한 공부 및 의견 감사 드립니다.
아래 문의 주신 내용에 대한 답변 입니다.

1. 218p ~223p 의 어덱티브 크루즈 컨트롤 예제는 객체 지향 모델링을 설명드린 의사코드(Pseudo code)입니다.
   소스코드 제공시 컴파일 오류가 없게만 만든것이지 실제 동작하는 코드는 아니라서 실행 결과를 제공해 드리지 않았습니다.

2. attack_special(player)가 맞습니다. 오탈자네요. 정오표에 추가 하겠습니다. 감사합니다.

3. 조판에 해당 (빗금 안처진 부분)의 폰트가 잘 못 지정되어 있는 것 같습니다. 정오표에 추가하고 다음쇄에 반영 하도록 하겠습니다.

내용 확인하시고 Issue Close도 부탁 드리겠습니다.

감사합니다.
