### ISSUE TITLE
챕터9 353p, 369p 오탈자 문의

### ISSUE THREAD

**Issue by JangIn-40** [mystous/DoItCPP#7]
안녕하세요 저자님 다시 책 잘 읽고 있습니다.
이건 아닐수도 있을거 같은데 353p 밑에서 세번째 줄에 케릭터와 라고 되어있는데 캐릭터와 일 것 같습니다. 그리고 369p 두번째 문단 두번째 줄에 의존성 역적 원칙을 이 아니라 의존성 역전 원칙을 이 되어야 할 것 같습니다.
다시 완독까지 힘내보도록 하겠습니다. 감사합니다!

**Comment by mystous** [comment]
안녕하세요?

말씀해주신 2가지 모두 오타 맞습니다. 오늘도 꼼꼼한 독서 및 학습 감사 드립니다.
아래 커밋으로 정오표에 추가 되었습니다. 
10a459424e45d4a4a392c5dd0b6510014bf3961b

오타 확인이어서 이 이슈는 제가 종료 하도록 하겠습니다.

감사합니다.
