### ISSUE TITLE
챕터 10 381p, 317p 템플릿 관련 질문 

### ISSUE THREAD

**Issue by JangIn-40** [mystous/DoItCPP#8]
안녕하세요 저자님 책 잘 읽고 있습니다.
다름이 아니라 381p 전체적으로 템플릿이 데이터 형식 추론을 한다라고 적혀있는데 317p 2번째 문단 두번째 줄에 C++언어는 auto변수 외에는 형식 추론을 하지 않으므로라고 적혀있어 의문이 생겨 질문 드립니다. 감사합니다.

**Comment by mystous** [comment]
안녕하세요?

C++은 데이터 형식이 사전에 정의된 형태로 사용하는 언어입니다.
명확하고 빠르지만 형식을 연역하는 편이 편한 경우가 있습니다. 이럴때 사용하는 것이 auto 입니다.
317p에서 바인딩에서 설명드린 내용입니다. **사용자가 사용하는 변수의 데이터 형식을 추론**하는 것이죠.

지금 공부하시는 템플릿은 데이터 형식의 제한을 두지 않고 다양한 데이터 형식을 사용할 수 있는 방법입니다.
동적 바인딩과는 다르게 템플릿은 데이터 형식을 추론 하여 해당 데이터 형식으로 된 코드 블럭을 컴파일러가 생성하합니다.
이런 기능을 인스턴스화라고 합니다. 이때 함수 템플릿이나 클래스 템플릿에 데이터 형식을 명시적으로 알려주지 않으면 컴파일러가 인스턴스화를 위하여 **입력된 매개변수의 데이터 형식을 추론**합니다. 그래야지만 매개변수의 데이터 형식에 맞는 코드 블럭을 인스턴스화 할 수 있기 때문입니다.  

개발자가 사용하는 변수의 데이터 형식을 추론할 수 있는 데이터 형식은 auto 뿐인 것이 맞습니다. 즉, **개발자가 사용하는 변수의 데이터 형식을 추론하여 사용**할 수 있개 해주는 것입니다.
템플릿에서는 인스터를 화를 위하여 컴파일러가 매개변수 데이터 형식을 추론하기 때문에 개발자가 사용하지는 않습니다.
개발자는 함수 템플릿을 호출 하거나, 클래스 템플릿을 사용합니다. **개발자는 내부의 추론이 어떻게 되는지 상관할 필요 없이 사용**하기만 하면 됩니다. 

방금 설명드린 것이 질문 주신 추론의 차이이며, **개발자가 직접 사용하는 변수의 데이터 형식 중 추론이 가능한 형식은 auto 뿐입니다.** 

추가 설명이 필요하시면 질문 주시면 다시 한 번 답변 드리도록 하겠습니다. :)
설명이 충분하셨다면 내용 확인하시고 Issue close도 부탁 드립니다.

감사합니다.
