### ISSUE TITLE
챕터 11 408p std::string의 '\0' 관련 질문

### ISSUE THREAD

**Issue by JangIn-40** [mystous/DoItCPP#9]
안녕하세요 저자님. 책 잘 읽고 있습니다.
다름이 아니라 더 408p 더 알아보기!에서 2번째 줄에 std::string에는 '\0'가 붙지 않는다 하셨는데 궁금해서 실험을 해봤습니다.
```
string str1("Hello");
	cout << str1 << endl;
	cout << str1.length() << endl;
	cout << str1.size() << endl;
	int i = 0;

	while (str1[i] != '\0')
	{
		i++;
	}
	cout << i << endl;
```

이 코드가 무한루프에 빠지지 않고 실행을 끝마치고 실행의 결과값은 
Hello
5
5
5
이던데 이건 어째서 실행이 되는지 궁금하여 문의를 드립니다. size()가 5인 것을 보아 '\0'이 붙진 않는 것 같은데 컴파일러가 알아서 '\0'는 문자열의 끝을 의미하는 것이라고 받아들이는 것일까요?

**Comment by DesignMoon** [comment]
먼저 이런 궁금함을 직접 실험 코드로 만들어 공부하는 방법은 너무나 환영하는바 입니다.
의문점에 대한 실험은 본질과 원리를 이해하는 가장 좋은 방법이기 때문이죠.

다시 본론으로 돌아와 질문에 대한 답변을 조금 길게 드리고자 합니다.

먼저 std::string 클래스는 null 문자를 문자열의 끝으로 사용하지 않으므로, while 반복문이 올바르게 작동하지 않을 수 있습니다.
std::string에서 operator[]를 사용하여 문자에 접근할 때, 인덱스 범위를 벗어나면 'undefined behavior' 가 발생합니다.
즉, 프로그램이 예측할 수 없는 동작을 할 수 있다는 의미지요.

"Hello"는 다섯 개의 문자로 구성되어 있으므로 index는 0부터 4까지만 유효합니다.
str1[5]로 접근하면 문자열의 범위를 벗어나게 됩니다.
이 경우, 프로그램이 정상적으로 실행되지 않을 수 있으며, 컴파일러에 따라 다르게 동작할 수 있습니다.
다행히도 Visual Studio 컴파일러에서 안전하게 처리해줬다고 해석하는 것이 맞습니다.

실제로 str1에 "Hello" 문자열이 어떻게 들어가는지는, 디버깅을 해보면 직접 확인할 수 있습니다.
https://learn.microsoft.com/ko-kr/visualstudio/debugger/getting-started-with-the-debugger-cpp?view=vs-2022

Visual Studio에서 디버깅하는 방법은 위의 링크에서
"중단점 설정 및 디버거 시작"  과 "자동 및 지역 창을 사용하여 변수 검사"
부분을 보시면, 충분히 따라하실 수 있으리라 생각합니다 :)

답변이 충분했다면 close 부탁드리겠습니다.
그리고 끝까지 화이팅입니다!

**Comment by JangIn-40** [comment]
친절한 답변 감사합니다 :)
